### PR TITLE
Fix Mark Attendance bug while loading the json

### LINKED ISSUE #143: Mark Attendance bug while loading the json
I have found a bug regarding the loading of the week number / mark attendance:

Here are the steps to reproduce it:
1. First, delete the current addressbook.json file in the data folder
2. Then run the application
3. Type list in the command box
4. Then quit the application and re-run it again.

I think this might be the problem:
```
{
    "name" : "Roy Balakrishnan",
    "phone" : "92624417",
    "email" : "royb@example.com",
    "matNum" : "A0000060M",
    "tutGroup" : "",
    "labGroup" : "B10",
    "faculty" : "",
    "year" : "",
    "remark" : "",
    "attendances" : "", <----- this line here
    "labScores" : "4.-|-|-|-",
    "tags" : [ "colleagues" ],
    "teleHandle" : "@roynan"
  }
```

This is the console logs for debugging (if necessary):
Image

### PR DESCRIPTION
**Pull request by philbertshea**
Mark Attendance Bug was found when loading the JSON.
Later, it was identified to be an incompatibility with the new empty attendance list.

Let's
* Update AttendanceList to support the new empty attendance list

Closes #143.

### CODE REVIEW

File: src/main/java/seedu/tassist/model/person/AttendanceList.java [hunk 1]
```diff
@@ -37,24 +37,40 @@ private AttendanceList() {
     }
 
     /**
-     * Checks if attendanceString has 13 digits, each digit being 0, 1, or 2.
+     * Checks if attendanceString has 13 digits, each digit being 0, 1, 2 or 3.
      * @param attendanceString Attendance String to check.
      * @return Boolean representing whether attendanceString is valid.
      */
-    public static boolean isValidAttendanceString(String attendanceString) {
+    public static boolean isValidNonEmptyAttendanceString(String attendanceString) {
```
Comment (ChinZJ) [inline src/main/java/seedu/tassist/model/person/AttendanceList.java:44]: Would it make more sense to generalize this to accept numbers fewer than 13? And if so, the system will auto append the default attendance (maybe no tutorial)?

**Review by ChinZJ — COMMENTED** [review]
Minor suggestion for consideration, else LGTM!

File: src/main/java/seedu/tassist/model/person/AttendanceList.java (hunk 1 above)
Comment (philbertshea) [reply src/main/java/seedu/tassist/model/person/AttendanceList.java:44]: Hmm, I get what you mean. I'm just thinking that it's better to restrict the attendance string to be either empty, or of length 13. Because if we accept a string shorter than 13, we are making the assumption that the digits start from week 1. (length 5 --> weeks 1-5). Similarly, we could then use the same idea to accept a string longer than 13, and add code to truncate anything beyond the 13th character. So from the perspective of isValidAttendanceString, I think it makes sense to only view strings of length 13 as valid. (Also note that this method is technically used "internally", meaning that the user doesn't actually pass in an attendance string in add, edit or att, hence I feel it's ok to be a bit stricter for internal use.)
