### PR TITLE
Bug fix: Update edit command & Cosmetic changes

### LINKED ISSUE #180: Standardise the absence of a value for edit messages
Description

Editing multiple persons will give a message like this:
Image
whereby if there is no value, it simply shows nothing. E.g. `Year: ,`

Steps to reproduce
Any edit command involving multiple people.

Expected
Message that shows "-" if an attribute is empty, e.g. Year

Actual
Shows Year: ,

Consider:
* Adding a dash "-" similar to the output message for non-existent values when a single person is edited

### LINKED ISSUE #181: Check conditional attributes in edit command
Description
If an optional or conditional attribute gets edited to "nothing", such that it breaks the requirement of a person to exist,
the app will basically blank out and crash.

Reproduce it
edit -i 1 -p
edit -i 1 -t

Expected
Error saying a person must minimally have phone or telegram handle!

Actual:
Attribute gets deleted and app blanks out.

Image

Let's
* Ensure conditional attributes (e.g. phone and telehandle - either one minimally) are all fulfilled before granting the edit to be executed

### LINKED ISSUE #182: Show Attendance List as "-" when displaying attributes
Description
After editing a person's tutorial group to nothing, the empty attendance list does not get shown as a dash.

Reproduce
edit -i 1 -t

Expected: 
Edit message xxx AttendanceList: -

Actual:
Edit message xxx AttendanceList: 

Image

Consider:
* Updating line 119 in Messages.java to .append(person.getAttendanceList().value.isEmpty() ? "-" : person.getAttendanceList())
* Alternatively, you could consider removing attendance list for display. After all, the digits might not really make sense to the user, so I'm not sure if displaying this as an attribute to the user adds value

### LINKED ISSUE #183: Update edit command message to explain errors
Description
Edit command message usage does not explain what can be edited to nothing (e.g. optional attributes)
and what cannot be edited to nothing.

Reproduce
edit -i 1 -t
edit -i 1 -n

Expected
Success!
Failure with explanation: Name is a mandatory field. (Or add that to message usage)

Actual
Success!
Failure but no explanation (why can't I remove a name?)

Image

Let's
* Update message usage to explain this constraint

### LINKED ISSUE #189: Minor formatting issue in edit message usage
The last line  edit -i1-3 is missing a space between -i and 1 and between 5 and -t
Image

### LINKED ISSUE #195: Show "invalid command format" message for edit command
Description
Edit command should show the suggested command format, when invalid tags are provided.

Reproduce
`edit -i 1 -www 3`

Expected
Invalid command format message, with suggested usage.

Actual
Image

### PR DESCRIPTION
**Pull request by aquaimpact**
## Functional Issues this closes:
Closes #181 
Closes #183
(these are talking about the same thing)

### Command 1
`edit -i 1 -p` (when the person only has a phone number. He does not have a telegram handle)

### Result 1
image

### Command 2
`edit -i 1 -b` ( when the person only has a lab group. He does not have a tutorial group)

### Result 2
image

### TODO before closing

- [x] Update JUnits for edit
- [x] Add JUnits for Batch edit
- [ ] Add error explanations

## Cosmetic Issues this closes:
Closes #180 
Closes #182
Closes #189 
Closes #195

### CODE REVIEW

File: src/main/java/seedu/tassist/logic/parser/EditCommandParser.java [hunk 1]
```diff
@@ -27,53 +28,72 @@
...
     /**
      * Parses the given {@code String} of arguments in the context of the EditCommand
      * and returns an EditCommand object for execution.
      * @throws ParseException if the user input does not conform the expected format
      */
     public EditCommand parse(String args) throws ParseException {
         requireNonNull(args);
+
+        // Ensure an even number of quotes.
+        if (!new QuotePattern().test(args)) {
```
Comment (philbertshea) [inline src/main/java/seedu/tassist/logic/parser/EditCommandParser.java:44]: Nice attention to detail.

File: src/test/java/seedu/tassist/logic/commands/EditCommandTest.java [hunk 2]
```diff
@@ -197,5 +212,53 @@ public void toStringMethod() {
         assertEquals(expected, editCommand.toString());
     }
 
-    // TODO: JUnits for batch editing
+    // ================= JUnits for Mandatory (Optional) Param =================
+    @Test
+    public void execute_validateAtLeastOneMandatoryFieldPresent_failure() {
+        model.addPerson(BADBOB);
```
Comment (philbertshea) [inline src/test/java/seedu/tassist/logic/commands/EditCommandTest.java:218]: BADBOB. LOL

**Review by philbertshea — APPROVED** [review]
Looks good to me.
