### PR TITLE
Support all contacts update max score and minor bug fixes for Lab

### LINKED ISSUE #173: Lab max score default not explicitly stated
Description
Max score default of 25 not explicitly mentioned within error message

Screenshot

Image

### LINKED ISSUE #174: No user feedback when invalid index is provided
Steps to reproduce 
Input and invalid index

Expected 
Error thrown

Actual 
Nothing

### LINKED ISSUE #175: Lab command overriding of flags
Description 

Last flag overrides previous flag for duplicates.

### LINKED ISSUE #177: Lab score update message syntax
Updating lab score shows debugging oriented message

Steps to reproduce
Update the `-sc` of any record

Screenshots

Image

### LINKED ISSUE #201: Support all contacts update max score
Update the `updateMaxScore` function to apply to all contacts.

### PR DESCRIPTION
**Pull request by hsinyilow**
When updating max score for the specified lab, the changes will now reflect for all contacts. 
Closes #201 

Bug fixes:

- Prevent duplicate flags: Closes #175 
- Added a footnote about the default max score value: Closes #173 
- Edited success message syntax to make it less debugging orientated: Closes #177 
- Not sure why not showing in v1.4 jar file but there is feedback when tested within intellij: Closes #174

### CODE REVIEW

File: src/main/java/seedu/tassist/logic/commands/UpdateLabScoreCommand.java [hunk 1]
```diff
@@ -30,14 +37,15 @@ public class UpdateLabScoreCommand extends Command {
...
+            + "Note: There default max score for all labs is 25.\n";
 
     public static final String MESSAGE_INVALID_LAB_NUMBER = "This lab does not exist."
-                    + "There are only %1$d labs";
+            + "There are only %1$d labs";
 
     public static final String MESSAGE_INVALID_SCORE =
             "The updated score cannot exceed the maximum score for the lab."
-            + "Your input: %1$d. The maximum score for this lab: %2$d.";
+                    + "Your input: %1$d. The maximum score for this lab: %2$d.";
```
Comment (ChinZJ) [inline src/main/java/seedu/tassist/logic/commands/UpdateLabScoreCommand.java:48]: Tab?

File: src/main/java/seedu/tassist/logic/commands/UpdateLabScoreCommand.java [hunk 2]
```diff
@@ -100,36 +109,74 @@ public UpdateLabScoreCommand(Index index, int labNumber, int labScore, int maxLa
...
-            newLabScoreList = personToUpdate.getLabScoreList().updateLabScore(labNumber, labScore);
-            break;
+            throw new CommandException("Error");
+        }
+
+        return new CommandResult(successMessage);
+    }
+
+    /**
+     * Refreshes all the contacts maxLabScore with the updated version.
```
Comment (ChinZJ) [inline src/main/java/seedu/tassist/logic/commands/UpdateLabScoreCommand.java:149]: Minor nitpick, maxLabScore should be encapsulated in <@code>, I cant really remember what the format is sorry.

File: src/main/java/seedu/tassist/logic/parser/UpdateLabScoreCommandParser.java [hunk 3]
```diff
@@ -29,45 +32,51 @@ public UpdateLabScoreCommand parse(String args) throws ParseException {
...
+        } else {
+            index = DEFAULT_INDEX;
+        }
+
         labNumber = ParserUtil.parseLabNumber(argMultimap.getValue(PREFIX_LAB_NUMBER).orElse(""));
 
+
         try {
-            if (isBothScorePresent || isOnlyLabScorePresent) {
+            if (isLabScorePresent) {
```
Comment (ChinZJ) [inline src/main/java/seedu/tassist/logic/parser/UpdateLabScoreCommandParser.java:63]: Not sure if it is better to merge the if blocks to reduce the number of checks

**Review by ChinZJ — COMMENTED** [review]
Nitpick on format, otherwise LGTM!

File: src/main/java/seedu/tassist/logic/parser/UpdateLabScoreCommandParser.java (hunk 3 above)
Comment (hsinyilow) [reply src/main/java/seedu/tassist/logic/parser/UpdateLabScoreCommandParser.java:63]: `isBothScorePresent` is an extension of `isLabScorePresent`. It is ok to reduce the checks because if`isBothScorePresent`  is true, then `isLabScorePresent `is true, but not vice versa.

**Review by hhlh27 — APPROVED** [review]
LGTM
