### PR TITLE
Fix toggle display UI bug

### LINKED ISSUE #281: [PE-D][Tester A] Toggle View Bug
For the feature toggle, some of the entries aren't consistent as seen in the screenshot. Even though there are both not selected, one of them (entry no. 3) shows information such as phone number and telegram handle while the other (entry no 4) do not.

This bug can be reproduced by using the toggle command a few times.

Steps taken:
1. Launch the app
2. enter toggle command once
3. enter toggle command again
4. scroll to the bottom

It can be seen that entry 6 is not consistent with the other entries.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: CXl0l0/ped#4

### PR DESCRIPTION
**Pull request by ChinZJ**
closes #281

### CODE REVIEW

File: src/main/java/seedu/tassist/ui/PersonListPanel.java [hunk 1]
```diff
@@ -34,8 +34,10 @@ public PersonListPanel(ObservableList<Person> personList, BooleanProperty compac
         personListView.setItems(personList);
         personListView.setCellFactory(listView -> new PersonListViewCell());
 
-        compactView.addListener((obs,
-                                 oldVal, newVal) -> personListView.refresh());
+        compactView.addListener((observable, oldVal, newVal) -> {
```
Comment (philbertshea) [inline src/main/java/seedu/tassist/ui/PersonListPanel.java:37]: Looks like a possible solution to the toggle issue on the UI side. Looks good to me!

File: src/main/resources/view/DarkTheme.css [hunk 2]
```diff
@@ -128,6 +128,7 @@
     -fx-font-family: "Segoe UI Semibold";
     -fx-font-size: 16px;
     -fx-text-fill: #010504;
+    -fx-wrap-text: true;
```
Comment (philbertshea) [inline src/main/resources/view/DarkTheme.css:131]: Looks good to me.

**Review by philbertshea — APPROVED** [review]
Looks like a good update to me.

**Comment by philbertshea** [comment]
Also, a low in LoC update. Great!
